application: pigeon-phoenix
version: 1
runtime: go
api_version: go1
# threadsafe: yes

handlers:

- url: /css
  static_dir: public/stylesheets

- url: /js
  static_dir: public/js

- url: /.*
  script: _go_app
  secure: always